spring.application.name=school-management
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/school_db
spring.datasource.username=postgres
spring.datasource.password=abhi@11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=./uploads/employee_docs
